# Generated by Django 4.1.7 on 2023-03-01 00:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="guesses_left",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="game",
            name="max_guesses",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("guess_code", models.CharField(max_length=4)),
                ("correct_color_and_position", models.PositiveSmallIntegerField()),
                ("correct_color_only", models.PositiveSmallIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="guess",
            constraint=models.UniqueConstraint(fields=("game", "position"), name="unique_guess_position"),
        ),
    ]
